version: '3.8'

services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama

  app:
    build: .
    ports:
      - "7860:7860"
    environment:
      - OLLAMA_API_BASE=http://ollama:11434
    depends_on:
      - ollama

volumes:
  ollama-data:
